# Generated by Django 2.1.7 on 2019-05-25 01:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotName', models.CharField(max_length=200)),
                ('numSpots', models.IntegerField()),
                ('occupiedSpots', models.IntegerField()),
                ('imageURL', models.URLField()),
                ('lotPosition', geoposition.fields.GeopositionField(blank=True, default='39.958, -75.601', max_length=42, null=True)),
                ('lastUpdate', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 25, 1, 28, 4, 275014, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='parkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('position', geoposition.fields.GeopositionField(blank=True, default='39.958, -75.601', max_length=42, null=True)),
                ('occupied', models.BooleanField(default=False)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkingLot')),
            ],
        ),
    ]
