# Generated by Django 2.1.7 on 2019-04-04 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotName', models.CharField(max_length=200)),
                ('numSpots', models.IntegerField()),
                ('occupiedSpots', models.IntegerField()),
                ('imageURL', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='parkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.IntegerField()),
                ('left', models.IntegerField()),
                ('right', models.IntegerField()),
                ('bottom', models.IntegerField()),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('occupied', models.BooleanField()),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkingLot')),
            ],
        ),
    ]
