# Generated by Django 2.2 on 2019-04-16 05:55

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20190403_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='parkingspot',
            name='longitude',
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='position',
            field=geoposition.fields.GeopositionField(default='null', max_length=42),
        ),
    ]
