# Generated by Django 2.2 on 2019-04-16 06:03

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20190416_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='position',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
