# Generated by Django 2.2 on 2019-04-25 13:45

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20190416_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='segmentedImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='imageURL',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='occupied',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='position',
            field=geoposition.fields.GeopositionField(max_length=42, null=True),
        ),
        migrations.CreateModel(
            name='occupiedHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking.parkingSpot')),
            ],
        ),
    ]
