# Generated by Django 2.2 on 2019-05-06 02:56

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_auto_20190425_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupiedhistory',
            name='spot',
        ),
        migrations.AddField(
            model_name='occupiedhistory',
            name='totalSpots',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='segmentedImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, default='39.958, -75.601', max_length=42, null=True),
        ),
    ]
