# Generated by Django 2.2 on 2019-05-09 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20190506_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupiedhistory',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 9, 0, 34, 24, 191616)),
        ),
    ]
