# Generated by Django 2.2 on 2019-05-22 21:05

import datetime
from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_auto_20190509_0034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='occupiedHistory',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='image',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='segmentedImage',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 22, 21, 5, 14, 681224)),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='lotPosition',
            field=geoposition.fields.GeopositionField(blank=True, default='39.958, -75.601', max_length=42, null=True),
        ),
    ]
